<?php
/**
 * Netgo_Gwishlist extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 */
$favouritelist = $data = unserialize($_COOKIE['gwishlist']);
?>   
<div class="my-account">
	<div class="page-title title-buttons">
        <h1><?php echo $this->__('My Wishlist') ?></h1>
        <?php if(count($favouritelist) > 0 and $favouritelist!=''){	?>
            <div class="buttons-set">
				<a href="<?php echo Mage::getBaseUrl(); ?>gwishlist/gwishlist/addallitem" class="button btn-add btn-block" title="<?php echo $this->__('Add All to Cart') ?>"><span><span><?php echo $this->__('Add All to Cart') ?></span></a>
				<a href="<?php echo Mage::getBaseUrl(); ?>gwishlist/gwishlist/update" class="button btn-update" title="<?php echo $this->__('Update Wishlist') ?>"><span><span><?php echo $this->__('Update Wishlist') ?></span></span></a>
			</div>
		<?php } ?>
    </div>

	<?php if(count($favouritelist) > 0 and $favouritelist!=''){	?>
		<ul class="products-grid">
			<?php foreach($favouritelist as $k => $v){ 
			if($v['product_id'] != ''){
			$_product = Mage::getModel('catalog/product')->load($v['product_id']); ?>
				<li class="item">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(420); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName();?>"><?php echo $_product->getName();?></a></h2>
					<div class="price-box">
						<div class="regular-price">
							<div class="price"><?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?></div>
						</div>
					</div>
					<div class="actions">
						<?php if($_product->isSaleable()): ?>
	                        <button type="button" class="button btn-cart" onclick="setLocation('<?php echo Mage::getBaseUrl(); ?>gwishlist/gwishlist/additem/item/<?php echo $v['entity_id'];?>');" title="<?php echo $this->__('Add to Cart') ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	                    <?php else: ?>
	                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                    <?php endif; ?>
	                    <ul class="add-to-links">
	                    	<li><a href="<?php echo Mage::getBaseUrl() ?>gwishlist/gwishlist/configure/wlid/<?php echo $v['entity_id'];?>" class="btn-edit" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Edit') ?>"><?php echo $this->__('Edit') ?></a></li>
	                    	<li><a class="btn-remove btn-remove2" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Remove') ?>" onclick="return confirm('<?php echo Mage::helper('core')->quoteEscape($this->__('Are you sure you want to remove this product from your wishlist?'), true) ?>');" href="<?php echo Mage::getBaseUrl(); ?>gwishlist/gwishlist/removeitem/item/<?php echo $v['entity_id'];?>"><?php echo $this->__('Remove') ?></a></li>
	                    </ul>
					</div>
				</li>
			<?php }} ?>
		</ul>
	<?php }else{ ?>

	<p class="favouritelist-empty"><?php echo $this->__('You have no items in your Wishlist.') ?></p>
	<?php } ?>
</div>
